# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: pp-deploy
on:
  push:
    branches:
      - main  # 修改为你的主分支名称，比如master或main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # 使用你需要的Node.js版本
          registry-url: 'https://npm.pkg.github.com/'  # 设置GitHub Packages的注册表URL
          scope: '@your-org-or-username'  # 指定作用域，如果你的包名是@your-org/package，则需要此处设置@your-org
 
      - name: Install dependencies
        run: npm ci
 
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用GitHub的内置token来认证
